name: Kmore
favicon: null
layout_spectrum: 0.5387819623574615
typography_spectrum: 0.3285497680772096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.744650996522978
  saturation: 0.3183475632686168
  rhythmicContrast: 0.4323452184908092
purpose: []
